# Generated by Django 4.2.15 on 2025-02-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRateUsd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.IntegerField(max_length=8)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
