# Generated by Django 4.2.15 on 2025-02-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserateusd',
            name='course',
            field=models.FloatField(max_length=8),
        ),
    ]
