# Generated by Django 4.2.15 on 2025-02-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_courserateusd_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserateusd',
            name='created_at',
            field=models.DateField(),
        ),
    ]
