# Generated by Django 4.2.15 on 2025-02-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_courserateusd_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courserateusd',
            old_name='created_at',
            new_name='updated_at',
        ),
    ]
